CREATE TABLE gallery (
	id SERIAL PRIMARY KEY,
	path VARCHAR(200) NOT NULL,
	description VARCHAR(500) NOT NULL,
	likes INT default 0
);

INSERT INTO gallery (path, description)
VALUES ('images/americasmostwanted.jpg', 'Holy fuck I look like a serial killer'),
('images/aoa.jpg', 'AOAs and Heartbreaks'),
('images/beautiful.jpg', 'Me on my throne'),
('images/crew.jpg', 'Some wizards, some Muggles, all class.'),
('images/crushed.jpg', 'Volunteering: Not even once.'),
('images/drunk.jpg', 'That time I got drunk and drooled on myself in front of strangers'),
('images/duckface.jpg', 'The most attractive facial expression on Earth or beyond'),
('images/guesswho.jpg', 'The problem with playing board games with rudos is that they always cheat :('),
('images/heart.jpg', 'E> Be still, my beating heart <3'),
('images/heatray.jpg', 'What happens if I get too near children'),
('images/ilikeboyz.jpg', 'Hey cheerleaders, I got the new cheer.  So fab!'),
('images/lap.jpeg', 'I''m basically a lapdog'),
('images/minion.jpg', 'I walked around Chicago like this, it was not my best idea'),
('images/ohbb.jpg', 'Stare into my eyes...'),
('images/phonehome.jpg', 'Best smelling place in the Universe'),
('images/rvivr.jpg', 'I''m in this one I swear!'),
('images/slide.jpg', 'Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'),
('images/slugbuds.jpg', 'They see me sluggin'', they hatin''...'),
('images/trashhouse.jpg', 'Ew who lives like this?  Oh wait, right, me.'),
('images/twentyone.jpg', 'Birthday diva'),
('images/uhoh.jpg', 'Twenty stories over the Atlantic'),
('images/wedding.jpg', 'd''aww'),
('images/wedding2.jpg', 'Okay fine one actual kinda serious picture'),
('images/wedding3.jpg', 'b4 da drinks'),
('images/xmas.jpg', 'I only celebrate Christmas if it means I can wear makeup'),
('images/xmas2.jpg', 'Trimming the tree?  Did I use that right?'),
('images/ghost.jpg', 'A g-g-g-ghost!'),
('images/wut.jpg', 'Okay, this one defies description'),
('images/antilovepoem.jpg', 'Pretenious hipster poet'),
('images/purple.jpg', 'Fuzzy!'),
('images/pool.jpg','Just an ordinary night, sweeping the pool table'),
('images/fro.jpg', 'Grew my hair out a bit'),
('images/candy.jpg', 'Candy!'),
('images/glam.jpg', 'Glam af'),
('images/angryglam.jpg', 'Grrrrrrrrr'),
('images/glam2.jpg', 'So beautiful <3');