const galleryItems = [
    { id: 1, path: 'images/americasmostwanted.jpg', description: 'Holy fuck I look like a serial killer', likes: 0 },
    {id: 2, path: 'images/aoa.jpg', description: 'AOAs & Heartbreak', likes: 0},
    {id: 3, path: 'images/beautiful.jpg', description: 'Me on my throne', likes: 0},
    {id: 4, path: 'images/crew.jpg', description: 'A mixed group of Muggle and Wizard porters ready to cause a ruckus', likes: 0},
    {id: 5, path: 'images/crushed.jpg', description: 'Volunteering: Not even once.', likes: 0},
    {id: 6, path: 'images/drunk.jpg', description: 'That time I got drunk and drooled on myself in front of strangers', likes: 0},
    {id: 7, path: 'images/duckface.jpg', description: 'The most attractive facial expression on Earth or beyond', likes: 0},
    {id: 8, path: 'images/guesswho.jpg', description: 'The problem with playing board games with rudos is that they always cheat :(', likes: 0},
    {id: 9, path: 'images/heart.jpg', description: 'E> Be still, my beating heart <3', likes: 0},
    {id: 10, path: 'images/heatray.jpg', description: 'What happens if I get too near children', likes: 0}, 
    {id: 11, path: 'images/ilikeboyz.jpg', description: 'Hey cheerleaders, I got the new cheer.  So fab!', likes: 0},
    {id: 12, path: 'images/lap.jpeg', description: 'I\'m basically a lapdog', likes: 0},
    {id: 13, path: 'images/minion.jpg', description: 'I walked around Chicago like this and it was not a good idea', likes: 0},
    {id: 14, path: 'images/ohbb.jpg', description: 'Stare into my eyes...', likes: 0},
    {id: 15, path: 'images/phonehome.jpg', description: 'Best smelling place in the Universe', likes: 0},
    {id: 16, path: 'images/rvivr.jpg', description: 'I\'m in this one I swear!', likes: 0},
    {id: 17, path: 'images/slide.jpg', description: 'Wheeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee', likes: 0},
    {id: 18, path: 'images/slugbuds.jpg', description: 'They see me sluggin\', they hatin\'...', likes: 0},
    {id: 19, path: 'images/trashhouse.jpg', description: 'Ew who lives like this?  Oh wait, right, me.', likes: 0},
    {id: 20, path: 'images/twentyone.jpg', description: 'Birthday diva', likes: 0},
    {id: 21, path: 'images/uhoh.jpg', description: 'Twenty stories over the Atlantic', likes: 0},
    {id: 22, path: 'images/wedding.jpg', description: 'd\'aww', likes: 0},
    {id: 23, path: 'images/wedding2.jpg', description: 'Okay fine one actual kinda serious picture', likes: 0},
    {id: 24, path: 'images/wedding3.jpg', description: 'b4 da drinks', likes: 0},
    {id: 25, path: 'images/xmas.jpg', description: 'I only celebrate Christmas if it means I can wear makeup', likes: 0},
    {id: 26, path: 'images/xmas2.jpg', description: 'Trimming the tree?  Did I use that right?', likes: 0},
    {id: 27, path: 'images/ghost.jpg', description: 'A g-g-g-ghost!', likes: 0},
    {id: 28, path: 'images/wut.jpg', description: 'Okay, this one defies description', likes: 0},
    {id: 29, path: 'images/antilovepoem.jpg', description: 'Pretenious hipster poet', likes: 0},
    {id: 30, path:'images/purple.jpg', description: 'Fuzzy!', likes: 0},
    {id: 31, path: 'images/pool.jpg', description: 'Just an ordinary night, sweeping the pool table', likes: 0},
    {id: 32, path: 'images/fro.jpg', description: 'Grew my hair out a bit', likes: 0},
    {id: 33, path: 'images/candy.jpg', description: 'Candy!', likes: 0},
    {id: 34, path: 'images/glam.jpg', description: 'Glam af', likes: 0},
    {id: 35, path: 'images/angryglam.jpg', description: 'Grrrrrrrrr', likes: 0},
    {id: 36, path: 'images/glam2.jpg', description: 'So beautiful <3', likes: 0}


];

module.exports = galleryItems;